# Generated by Django 4.1 on 2022-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_quantity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='date',
            field=models.DateTimeField(verbose_name='Quantity as of Date'),
        ),
    ]
