# Generated by Django 4.1 on 2022-08-10 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_quantity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Quantity as of Time'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='date',
            field=models.DateField(verbose_name='Quantity as of Date'),
        ),
    ]
