# Generated by Django 4.1 on 2022-08-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_quantity_time_alter_quantity_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'ordering': ['-date', '-time']},
        ),
    ]
