# Generated by Django 4.1 on 2022-08-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_quantity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('origin', models.CharField(choices=[('N', 'Natural'), ('A', 'Animal'), ('M', 'Man Made')], default='N', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='yarn',
            name='fibre',
            field=models.ManyToManyField(to='main_app.fibre'),
        ),
    ]
