# Generated by Django 4.1 on 2022-08-11 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_fibre_yarn_fibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Quantity as of Time'),
        ),
    ]
